name: AutoAtmosBuilder

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - 'AutoAtmosBuilder.sh'
  schedule:
    - cron: '28 23 * * *'  # 每天北京时间7:30（UTC时间23:30）触发

env:
  SCRIPT_SH: AutoAtmosBuilder.sh
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main
    
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo -E apt install -y jq
    
    - name: "Build & Release"
      run: |
        set -e  # 出错时终止
        echo "DATE=$(date "+%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
        echo "tag_name=$(date +%Y%m%d)" >> $GITHUB_ENV
        chmod +x $SCRIPT_SH
        ./$SCRIPT_SH
        zip -rq SwitchSD.zip SwitchSD

    - name: Read description.txt
      id: description
      uses: juliangruber/read-file-action@v1
      with:
        path: ./description.txt

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.DATE }} ❤️ | 大气层雪的整合包 感谢九夏的脚本
        allowUpdates: true
        tag: ${{ env.tag_name }}
        commit: main
        token: ${{ secrets.RELEASE_TOKEN }}
        body: "${{ steps.description.outputs.content }}"
        artifacts: "SwitchSD.zip"

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.3.2
      with:
        keep_latest: 5
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
